using System.Text;

namespace Edict.Generators.Commands;

internal static class CommandGrainSpineEmitter
{
    public static string Emit(CommandHandlerGrainModel grain)
    {
        var interfaceName = "I" + grain.GrainName;
        var arms = new StringBuilder();

        foreach (var command in grain.Commands)
        {
            arms.Append("                ")
                .Append(command.Fqn)
                .Append(" c => this.ValidateAndHandleAsync(c, () => this.Handle(c)),\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{grain.Namespace}}
            {
                /// <summary>Generated Orleans grain interface for {{grain.GrainName}}.</summary>
                public partial interface {{interfaceName}} : global::Edict.Core.Commands.IEdictCommandHandler
                {
                }

                public partial class {{grain.GrainName}} : {{interfaceName}}
                {
                    public override async {{EdictWellKnownNames.TaskOfEdictCommandResultFqn}} DispatchAsync(
                        global::Edict.Contracts.Commands.EdictCommand command)
                    {
                        global::Edict.Contracts.Commands.EdictCommandResult result;
                        try
                        {
                            result = await (command switch
                            {
            {{arms.ToString().TrimEnd('\n')}}
                                _ => throw new global::Edict.Core.Commands.EdictUnroutableCommandException(
                                    command.GetType()),
                            });
                        }
                        catch
                        {
                            this.DiscardRaisedEvents();
                            throw;
                        }
                        if (result is global::Edict.Contracts.Commands.EdictCommandResult.Accepted)
                            await this.CommitAndDrainRaisedEventsAsync();
                        else
                            this.DiscardRaisedEvents();
                        return result;
                    }
                }
            }

            """;
    }
}
