using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Edict.Generators.Commands;

internal static class CommandRouteRegistrarEmitter
{
    public static string Emit(ImmutableArray<CommandHandlerGrainModel> grains)
    {
        var ordered = grains
            .OrderBy(g => g.GrainFqn, System.StringComparer.Ordinal)
            .ToArray();

        var entries = new StringBuilder();
        foreach (var grain in ordered)
        {
            var interfaceFqn =
                $"global::{grain.Namespace}.I{grain.GrainName}";

            foreach (var command in grain.Commands)
            {
                if (command.TelemeterizedProperties.IsEmpty)
                {
                    entries.Append("            routes[typeof(")
                        .Append(command.Fqn)
                        .Append(")] = new global::Edict.Core.Commands.CommandRoute(typeof(")
                        .Append(command.Fqn)
                        .Append("), typeof(")
                        .Append(interfaceFqn)
                        .Append("), \"")
                        .Append(grain.GrainTypeName)
                        .Append("\", command => ((")
                        .Append(command.Fqn)
                        .Append(")command).")
                        .Append(command.RouteKeyProperty)
                        .Append(");\n");
                }
                else
                {
                    var tagLines = new StringBuilder();
                    foreach (var property in command.TelemeterizedProperties)
                    {
                        var tagName = $"edict.{command.SimpleName.ToLowerInvariant()}.{property.PropertyName.ToLowerInvariant()}";
                        tagLines.Append("                    activity?.SetTag(\"")
                            .Append(tagName)
                            .Append("\", typedCommand.")
                            .Append(property.PropertyName)
                            .Append(");\n");
                    }

                    entries.Append("            routes[typeof(")
                        .Append(command.Fqn)
                        .Append(")] = new global::Edict.Core.Commands.CommandRoute(\n")
                        .Append("                typeof(").Append(command.Fqn).Append("),\n")
                        .Append("                typeof(").Append(interfaceFqn).Append("),\n")
                        .Append("                \"").Append(grain.GrainTypeName).Append("\",\n")
                        .Append("                command => ((").Append(command.Fqn).Append(")command).").Append(command.RouteKeyProperty).Append(",\n")
                        .Append("                (command, activity) =>\n")
                        .Append("                {\n")
                        .Append("                    var typedCommand = (").Append(command.Fqn).Append(")command;\n")
                        .Append(tagLines)
                        .Append("                });\n");
                }
            }
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            [assembly: global::Edict.Contracts.Routing.EdictRoutesAttribute(typeof(global::Edict.Generated.EdictRouteRegistrar))]

            namespace Edict.Generated
            {
                internal static class EdictRouteRegistrar
                {
                    public static void Register(
                        global::System.Collections.Generic.Dictionary<
                            global::System.Type, global::Edict.Core.Commands.CommandRoute> routes)
                    {
            {{entries.ToString().TrimEnd('\n')}}
                    }
                }
            }

            """;
    }
}
