using System.Text;

namespace Edict.Generators.Commands;

internal static class CommandGrainSpineEmitter
{
    public static string Emit(CommandHandlerGrainModel grain)
    {
        var interfaceName = "I" + grain.GrainName;
        var arms = new StringBuilder();

        foreach (var command in grain.Commands)
        {
            arms.Append("                ")
                .Append(command.Fqn)
                .Append(" c => this.ValidateAndHandleAsync(c, () => this.")
                .Append(EdictWellKnownNames.HandleMethodName)
                .Append("(c)),\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{grain.Namespace}}
            {
                /// <summary>Generated Orleans grain interface for {{grain.GrainName}}.</summary>
                public partial interface {{interfaceName}} : global::Edict.Core.Commands.IEdictCommandHandler
                {
                }

                public partial class {{grain.GrainName}} : {{interfaceName}}
                {
                    public override {{EdictWellKnownNames.TaskOfEdictCommandResultFqn}} DispatchAsync(
                        global::Edict.Contracts.Commands.EdictCommand command) =>
                        command switch
                        {
            {{arms.ToString().TrimEnd('\n')}}
                            _ => throw new global::Edict.Core.Commands.EdictUnroutableCommandException(
                                command.GetType()),
                        };
                }
            }

            """;
    }
}
