using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Edict.Generators.Commands;

/// <summary>
/// Per-command-type Send interceptor emitter. One specialisation
/// method per discovered Command, with N <c>[InterceptsLocation]</c> attribute
/// lines for the N concrete-typed call sites that bind to that command. Keeps
/// the generated diff small and gives "what does Send(OrderPlace) actually do"
/// a single grep target.
/// </summary>
internal static class SendInterceptorEmitter
{
    public sealed record TypeBundle(
        CommandModel Command,
        string GrainInterfaceFqn,
        string GrainClassName,
        EquatableArray<SendInvocationModel> Invocations);

    public static ImmutableArray<TypeBundle> Group(
        ImmutableArray<SendInvocationModel> invocations,
        ImmutableArray<CommandHandlerGrainModel> grains)
    {
        if (invocations.IsDefaultOrEmpty || grains.IsDefaultOrEmpty)
        {
            return ImmutableArray<TypeBundle>.Empty;
        }

        var commandToBundle = new Dictionary<string, (CommandModel command, string grainInterfaceFqn, string grainClassName)>(System.StringComparer.Ordinal);
        foreach (var grain in grains)
        {
            var grainInterfaceFqn = $"global::{grain.Namespace}.I{grain.GrainName}";
            foreach (var command in grain.Commands)
            {
                if (!commandToBundle.ContainsKey(command.Fqn))
                {
                    commandToBundle[command.Fqn] = (command, grainInterfaceFqn, grain.GrainTypeName);
                }
            }
        }

        var byCommand = new Dictionary<string, List<SendInvocationModel>>(System.StringComparer.Ordinal);
        foreach (var invocation in invocations)
        {
            if (!commandToBundle.ContainsKey(invocation.CommandFqn))
            {
                continue;
            }

            if (!byCommand.TryGetValue(invocation.CommandFqn, out var list))
            {
                list = new List<SendInvocationModel>();
                byCommand[invocation.CommandFqn] = list;
            }
            list.Add(invocation);
        }

        var builder = ImmutableArray.CreateBuilder<TypeBundle>(byCommand.Count);
        foreach (var commandFqn in byCommand.Keys.OrderBy(k => k, System.StringComparer.Ordinal))
        {
            var (command, grainInterfaceFqn, grainClassName) = commandToBundle[commandFqn];
            var ordered = byCommand[commandFqn]
                .OrderBy(i => i.DisplayLocation, System.StringComparer.Ordinal)
                .ThenBy(i => i.LocationData, System.StringComparer.Ordinal)
                .ToArray();
            builder.Add(new TypeBundle(
                command,
                grainInterfaceFqn,
                grainClassName,
                new EquatableArray<SendInvocationModel>(ordered)));
        }

        return builder.ToImmutable();
    }

    public static string Emit(TypeBundle bundle)
    {
        var command = bundle.Command;
        var sanitisedCommandFqn = SanitiseForIdentifier(command.Fqn);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("\n");
        sb.Append("namespace Edict.Generated\n");
        sb.Append("{\n");
        sb.Append("    file static class SendInterceptor_").Append(sanitisedCommandFqn).Append("\n");
        sb.Append("    {\n");

        foreach (var invocation in bundle.Invocations)
        {
            sb.Append("        // ").Append(invocation.DisplayLocation).Append('\n');
            sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(")
                .Append(invocation.LocationVersion)
                .Append(", \"")
                .Append(invocation.LocationData)
                .Append("\")]\n");
        }

        // Interceptor signatures must mirror the intercepted method exactly
        // (Roslyn 5.0): IEdictSender.SendAsync takes EdictCommand, so the
        // interceptor's parameter is also EdictCommand. The per-type knowledge
        // (route key property, telemeterized tags, grain interface) is baked
        // in via a direct cast inside — the call site is known to bind to a
        // concrete command type because that's how we discovered it.
        sb.Append("        public static global::System.Threading.Tasks.Task<global::Edict.Contracts.Commands.EdictCommandResult> InterceptSendAsync(\n");
        sb.Append("            this global::Edict.Contracts.Sending.IEdictSender sender,\n");
        sb.Append("            global::Edict.Contracts.Commands.EdictCommand command)\n");
        sb.Append("        {\n");
        sb.Append("            if (sender is global::Edict.Core.Commands.EdictSender es)\n");
        sb.Append("            {\n");
        sb.Append("                var typed = (").Append(command.Fqn).Append(")command;\n");
        sb.Append("                return es.SendFastPathAsync<")
            .Append(command.Fqn).Append(">(\n");
        sb.Append("                    typed,\n");
        sb.Append("                    typed.").Append(command.RouteKeyProperty).Append(",\n");
        sb.Append("                    \"").Append(command.SimpleName).Append("\",\n");
        sb.Append("                    \"").Append(bundle.GrainClassName).Append("\",\n");

        if (command.TelemeterizedProperties.IsEmpty)
        {
            sb.Append("                    extraTags: null);\n");
        }
        else
        {
            sb.Append("                    extraTags: static (c, a) =>\n");
            sb.Append("                    {\n");
            foreach (var prop in command.TelemeterizedProperties)
            {
                var tagName = $"{EdictWellKnownNames.TelemeterizedTagPrefix}{SnakeCaseLower.Convert(prop.PropertyName)}";
                sb.Append("                        a.SetTag(\"")
                    .Append(tagName)
                    .Append("\", c.")
                    .Append(prop.PropertyName)
                    .Append(");\n");
            }
            sb.Append("                    });\n");
        }

        sb.Append("            }\n");
        sb.Append("            return sender.SendAsync(command);\n");
        sb.Append("        }\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        sb.Append("\n");
        sb.Append("namespace System.Runtime.CompilerServices\n");
        sb.Append("{\n");
        sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]\n");
        sb.Append("    file sealed class InterceptsLocationAttribute : global::System.Attribute\n");
        sb.Append("    {\n");
        sb.Append("        public InterceptsLocationAttribute(int version, string data) { }\n");
        sb.Append("    }\n");
        sb.Append("}\n");

        return sb.ToString();
    }

    static string SanitiseForIdentifier(string fqn)
    {
        var trimmed = fqn.StartsWith("global::", System.StringComparison.Ordinal)
            ? fqn.Substring("global::".Length)
            : fqn;
        var sb = new StringBuilder(trimmed.Length);
        foreach (var ch in trimmed)
        {
            sb.Append(ch is '.' or '<' or '>' or ',' or ' ' or '+' ? '_' : ch);
        }
        return sb.ToString();
    }
}
