using System.Linq;
using System.Text;

namespace Edict.Generators.Projections;

internal static class ProjectionGrainSpineEmitter
{
    public static string Emit(ProjectionGrainModel grain)
    {
        var interfaceName = "I" + grain.GrainName;

        var streamNames = grain.Handlers
            .Select(h => h.StreamName)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(n => n, System.StringComparer.Ordinal)
            .ToArray();

        var subscriptionAttrs = new StringBuilder();
        foreach (var name in streamNames)
        {
            subscriptionAttrs
                .Append("    [global::Orleans.ImplicitStreamSubscriptionAttribute(\"")
                .Append(name)
                .Append("\")]\n");
        }

        var dispatchArms = new StringBuilder();
        foreach (var handler in grain.Handlers)
        {
            dispatchArms
                .Append("                case ").Append(handler.EventFqn).Append(" typed:\n")
                .Append("                {\n")
                .Append("                    var parentContext = ")
                .Append(EdictWellKnownNames.ActivityExtensionsFqn)
                .Append(".RestoreFromStrings(evt.TraceId, evt.SpanId, evt.TraceState);\n")
                .Append("                    using var span = ")
                .Append(EdictWellKnownNames.ActivitySourceExtensionsFqn)
                .Append(".StartEdictEventHandle(")
                .Append(EdictWellKnownNames.EdictDiagnosticsActivitySourceFqn)
                .Append(", \"").Append(handler.EventSimpleName).Append("\", parentContext);\n")
                .Append("                    await DispatchEventAsync(typed, Handle);\n")
                .Append("                    return true;\n")
                .Append("                }\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{grain.Namespace}}
            {
                /// <summary>Generated Orleans grain interface for {{grain.GrainName}}.</summary>
                public partial interface {{interfaceName}} : global::Edict.Core.Projections.IEdictProjectionBuilder
                {
                }

            {{subscriptionAttrs.ToString().TrimEnd('\n')}}
                public partial class {{grain.GrainName}} : {{interfaceName}}
                {
                    protected override async global::System.Threading.Tasks.Task<bool> DispatchAsync(
                        global::Edict.Contracts.Events.EdictEvent evt)
                    {
                        switch (evt)
                        {
            {{dispatchArms.ToString().TrimEnd('\n')}}
                            default:
                                return false;
                        }
                    }
                }
            }

            """;
    }
}
