using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Edict.Generators.Projections;

internal static class ProjectionReadRegistrarEmitter
{
    public static string Emit(ImmutableArray<ProjectionGrainModel> grains)
    {
        var ordered = grains
            .Where(grain => grain.RowFqn is not null)
            .OrderBy(grain => grain.GrainTypeName, System.StringComparer.Ordinal)
            .ToArray();

        var entries = new StringBuilder();
        foreach (var grain in ordered)
        {
            entries.Append("            routes[typeof(")
                .Append(grain.RowFqn)
                .Append(")] = \"")
                .Append(grain.GrainTypeName)
                .Append("\";\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            [assembly: global::Edict.Contracts.Routing.EdictProjectionReadRoutesAttribute(typeof(global::Edict.Generated.EdictProjectionReadRegistrar))]

            namespace Edict.Generated
            {
                internal static class EdictProjectionReadRegistrar
                {
                    public static void Register(
                        global::System.Collections.Generic.Dictionary<
                            global::System.Type, global::System.String> routes)
                    {
            {{entries.ToString().TrimEnd('\n')}}
                    }
                }
            }

            """;
    }
}
