using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Edict.Generators.EventStreamAccessors;

internal static class EventStreamRegistrarEmitter
{
    public static string Emit(ImmutableArray<EventStreamAccessorModel> events)
    {
        var ordered = events
            .OrderBy(e => e.Fqn, System.StringComparer.Ordinal)
            .ToArray();

        var entries = new StringBuilder();
        foreach (var evt in ordered)
        {
            entries.Append("            accessors[typeof(")
                .Append(evt.Fqn)
                .Append(")] = new global::Edict.Contracts.Routing.EdictEventStreamAccessor(\"")
                .Append(evt.StreamName)
                .Append("\", static evt => ((")
                .Append(evt.Fqn)
                .Append(")evt).")
                .Append(evt.RouteKeyProperty)
                .Append(");\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            [assembly: global::Edict.Contracts.Routing.EdictEventStreamsAttribute(typeof(global::Edict.Generated.EdictEventStreamRegistrar))]

            namespace Edict.Generated
            {
                internal static class EdictEventStreamRegistrar
                {
                    public static void Register(
                        global::System.Collections.Generic.Dictionary<
                            global::System.Type, global::Edict.Contracts.Routing.EdictEventStreamAccessor> accessors)
                    {
            {{entries.ToString().TrimEnd('\n')}}
                    }
                }
            }

            """;
    }
}
