using System.Linq;
using System.Text;

namespace Edict.Generators.EventHandler;

internal static class EventHandlerGrainSpineEmitter
{
    public static string Emit(EventHandlerGrainModel grain)
    {
        var interfaceName = "I" + grain.GrainName;

        var streamNames = grain.Handlers
            .Select(h => h.StreamName)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(n => n, System.StringComparer.Ordinal)
            .ToArray();

        var subscriptionAttrs = new StringBuilder();
        foreach (var name in streamNames)
        {
            subscriptionAttrs
                .Append("    [global::Orleans.ImplicitStreamSubscriptionAttribute(\"")
                .Append(name)
                .Append("\")]\n");
        }

        var handlesTypeArms = new StringBuilder();
        foreach (var handler in grain.Handlers)
        {
            handlesTypeArms
                .Append("                ").Append(handler.EventFqn).Append(" => true,\n");
        }

        // EdictEventHandler arms intentionally do NOT open an
        // edict.event.handle span — the InvokeHandlerExecutor already opened
        // one outer span using the entry's captured traceparent so the
        // deferred invocation nests correctly under the publish span across
        // backoff. Adding a per-arm span here would double-wrap every
        // invocation as two sibling spans under publish.
        var dispatchArms = new StringBuilder();
        foreach (var handler in grain.Handlers)
        {
            dispatchArms
                .Append("                case ").Append(handler.EventFqn).Append(" typed:\n")
                .Append("                {\n")
                .Append("                    await DispatchEventAsync(typed, Handle);\n")
                .Append("                    return true;\n")
                .Append("                }\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{grain.Namespace}}
            {
                /// <summary>Generated Orleans grain interface for {{grain.GrainName}}.</summary>
                public partial interface {{interfaceName}} : global::Edict.Core.Idempotency.IEdictEventConsumer
                {
                }

            {{subscriptionAttrs.ToString().TrimEnd('\n')}}
                public partial class {{grain.GrainName}} : {{interfaceName}}
                {
                    protected override bool HandlesType(
                        global::Edict.Contracts.Events.EdictEvent evt)
                    {
                        return evt switch
                        {
            {{handlesTypeArms.ToString().TrimEnd('\n')}}
                            _ => false,
                        };
                    }

                    protected override async global::System.Threading.Tasks.Task<bool> DispatchAsync(
                        global::Edict.Contracts.Events.EdictEvent evt)
                    {
                        switch (evt)
                        {
            {{dispatchArms.ToString().TrimEnd('\n')}}
                            default:
                                return false;
                        }
                    }
                }
            }

            """;
    }
}
