<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Edict.Benchmarks.Throughput</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Orleans.TestingHost" />
        <PackageReference Include="Microsoft.Orleans.Streaming.AzureStorage" />
        <PackageReference Include="Microsoft.Orleans.Persistence.AzureStorage" />
        <PackageReference Include="Microsoft.Orleans.Reminders.AzureStorage" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Edict.Contracts\Edict.Contracts.csproj" />
        <ProjectReference Include="..\Edict.Core\Edict.Core.csproj" />
        <ProjectReference Include="..\Edict.Azure.Streaming\Edict.Azure.Streaming.csproj" />
        <ProjectReference Include="..\Edict.Azure.Persistence\Edict.Azure.Persistence.csproj" />
        <ProjectReference Include="..\Edict.Substrate\Edict.Substrate.csproj" />
        <ProjectReference Include="..\Edict.Substrate.Azurite\Edict.Substrate.Azurite.csproj" />
        <ProjectReference Include="..\Edict.Substrate.KafkaPostgres\Edict.Substrate.KafkaPostgres.csproj" />
        <ProjectReference Include="..\Edict.Generators\Edict.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\Edict.Analyzers\Edict.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
