using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Edict.Generators.EventTagWriters;

internal static class EventTagWritersRegistrarEmitter
{
    public static string Emit(ImmutableArray<EventTagWritersModel> events)
    {
        var ordered = events
            .OrderBy(e => e.Fqn, System.StringComparer.Ordinal)
            .ToArray();

        var entries = new StringBuilder();
        foreach (var edictEvent in ordered)
        {
            entries.Append("            writers[typeof(")
                .Append(edictEvent.Fqn)
                .Append(")] = static (e, a) =>\n")
                .Append("            {\n")
                .Append("                var typed = (").Append(edictEvent.Fqn).Append(")e;\n");
            foreach (var property in edictEvent.TelemeterizedProperties)
            {
                var tagName = $"{EdictWellKnownNames.TelemeterizedTagPrefix}{SnakeCaseLower.Convert(property.PropertyName)}";
                entries.Append("                a.SetTag(\"")
                    .Append(tagName)
                    .Append("\", typed.")
                    .Append(property.PropertyName)
                    .Append(");\n");
            }
            entries.Append("            };\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            [assembly: global::Edict.Contracts.Routing.EdictEventTagWritersAttribute(typeof(global::Edict.Generated.EdictEventTagWritersRegistrar))]

            namespace Edict.Generated
            {
                internal static class EdictEventTagWritersRegistrar
                {
                    public static void Register(
                        global::System.Collections.Generic.Dictionary<
                            global::System.Type,
                            global::System.Action<
                                global::Edict.Contracts.Events.EdictEvent,
                                global::System.Diagnostics.Activity>> writers)
                    {
            {{entries.ToString().TrimEnd('\n')}}
                    }
                }
            }

            """;
    }
}
