<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Data.Tables" />
        <PackageReference Include="Azure.Storage.Blobs" />
        <PackageReference Include="Azure.Storage.Queues" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Orleans.Server" />
        <PackageReference Include="Microsoft.Orleans.Client" />
        <PackageReference Include="Testcontainers.Azurite" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Edict.Substrate\Edict.Substrate.csproj" />
        <ProjectReference Include="..\Edict.Contracts\Edict.Contracts.csproj" />
        <ProjectReference Include="..\Edict.Core\Edict.Core.csproj" />
        <ProjectReference Include="..\Edict.Azure.Streaming\Edict.Azure.Streaming.csproj" />
        <ProjectReference Include="..\Edict.Azure.Persistence\Edict.Azure.Persistence.csproj" />
    </ItemGroup>

</Project>
