using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Edict.Generators.Commands;

namespace Edict.Generators.Events;

/// <summary>
/// Per-event-type Raise interceptor emitter. One typed
/// specialisation method per discovered Event, with N
/// <c>[InterceptsLocation]</c> attribute lines for every concrete-typed
/// <c>Raise(...)</c> call site. The body forwards to
/// <c>EdictCommandHandler.RaiseFast&lt;TEvent&gt;</c> so the typed call site
/// stays monomorphic; the buffer add + <c>OccurredAt</c> stamp are identical
/// to the base method.
/// </summary>
internal static class RaiseInterceptorEmitter
{
    public sealed record TypeBundle(
        string EventFqn,
        string EventSimpleName,
        EquatableArray<RaiseInvocationModel> Invocations);

    public static ImmutableArray<TypeBundle> Group(ImmutableArray<RaiseInvocationModel> invocations)
    {
        if (invocations.IsDefaultOrEmpty)
        {
            return ImmutableArray<TypeBundle>.Empty;
        }

        var byEvent = new Dictionary<string, List<RaiseInvocationModel>>(System.StringComparer.Ordinal);
        foreach (var invocation in invocations)
        {
            if (!byEvent.TryGetValue(invocation.EventFqn, out var list))
            {
                list = new List<RaiseInvocationModel>();
                byEvent[invocation.EventFqn] = list;
            }
            list.Add(invocation);
        }

        var builder = ImmutableArray.CreateBuilder<TypeBundle>(byEvent.Count);
        foreach (var eventFqn in byEvent.Keys.OrderBy(k => k, System.StringComparer.Ordinal))
        {
            var ordered = byEvent[eventFqn]
                .OrderBy(i => i.DisplayLocation, System.StringComparer.Ordinal)
                .ThenBy(i => i.LocationData, System.StringComparer.Ordinal)
                .ToArray();
            builder.Add(new TypeBundle(
                eventFqn,
                StripToSimpleName(eventFqn),
                new EquatableArray<RaiseInvocationModel>(ordered)));
        }

        return builder.ToImmutable();
    }

    public static string Emit(TypeBundle bundle)
    {
        var sanitised = SanitiseForIdentifier(bundle.EventFqn);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("\n");
        sb.Append("namespace Edict.Generated\n");
        sb.Append("{\n");
        sb.Append("    file static class RaiseInterceptor_").Append(sanitised).Append("\n");
        sb.Append("    {\n");

        foreach (var invocation in bundle.Invocations)
        {
            sb.Append("        // ").Append(invocation.DisplayLocation).Append('\n');
            sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(")
                .Append(invocation.LocationVersion)
                .Append(", \"")
                .Append(invocation.LocationData)
                .Append("\")]\n");
        }

        // Interceptor signatures must mirror the intercepted method exactly
        // (Roslyn 5.0). Raise lives on EdictCommandHandler<TState>, so the
        // receiver is generic and TState gets inferred from the call-site
        // type. The per-event-type knowledge is preserved by a direct cast.
        sb.Append("        public static void InterceptRaise<TState>(\n");
        sb.Append("            this global::Edict.Core.Commands.EdictCommandHandler<TState> self,\n");
        sb.Append("            global::Edict.Contracts.Events.EdictEvent theEvent)\n");
        sb.Append("            where TState : global::Edict.Contracts.Persistence.IEdictPersistedState, new()\n");
        sb.Append("            => self.RaiseFast<").Append(bundle.EventFqn).Append(">((").Append(bundle.EventFqn).Append(")theEvent);\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        sb.Append("\n");
        sb.Append("namespace System.Runtime.CompilerServices\n");
        sb.Append("{\n");
        sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]\n");
        sb.Append("    file sealed class InterceptsLocationAttribute : global::System.Attribute\n");
        sb.Append("    {\n");
        sb.Append("        public InterceptsLocationAttribute(int version, string data) { }\n");
        sb.Append("    }\n");
        sb.Append("}\n");

        return sb.ToString();
    }

    static string StripToSimpleName(string fqn)
    {
        var trimmed = fqn.StartsWith("global::", System.StringComparison.Ordinal)
            ? fqn.Substring("global::".Length)
            : fqn;
        var lastDot = trimmed.LastIndexOf('.');
        return lastDot >= 0 ? trimmed.Substring(lastDot + 1) : trimmed;
    }

    static string SanitiseForIdentifier(string fqn)
    {
        var trimmed = fqn.StartsWith("global::", System.StringComparison.Ordinal)
            ? fqn.Substring("global::".Length)
            : fqn;
        var sb = new StringBuilder(trimmed.Length);
        foreach (var ch in trimmed)
        {
            sb.Append(ch is '.' or '<' or '>' or ',' or ' ' or '+' ? '_' : ch);
        }
        return sb.ToString();
    }
}
