<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="MessagePack" />
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
        <PackageReference Include="Microsoft.Orleans.TestingHost" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Edict.Contracts\Edict.Contracts.csproj" />
        <ProjectReference Include="..\Edict.Core\Edict.Core.csproj" />
        <ProjectReference Include="..\Edict.Telemetry\Edict.Telemetry.csproj" />
        <ProjectReference Include="..\Edict.Generators\Edict.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
        <ProjectReference Include="..\Edict.Analyzers\Edict.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
