namespace Edict.Generators.Shared;

/// <summary>
/// Emits the Orleans <c>[Alias]</c> + MessagePack <c>[MessagePackObject(true)]</c>
/// partial declaration for either an Edict command or an Edict event — the
/// template is identical (ADR-0007 round-trip relies on the simple type name),
/// so one emitter serves both concepts.
/// </summary>
internal static class SharedAliasEmitter
{
    public static string Emit(string typeNamespace, string simpleName) =>
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace {{typeNamespace}}
        {
            [global::Orleans.AliasAttribute("{{simpleName}}")]
            [global::MessagePack.MessagePackObjectAttribute(true)]
            public partial record {{simpleName}};
        }

        """;
}
