<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>sample-apphost-kafkapostgres-edict</UserSecretsId>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <Sdk Name="Aspire.AppHost.Sdk" Version="13.3.1" />

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" />
        <PackageReference Include="Aspire.Hosting.Kafka" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Sample.KafkaPostgres.Silo/Sample.KafkaPostgres.Silo.csproj" />
        <ProjectReference Include="../Sample.KafkaPostgres.Web/Sample.KafkaPostgres.Web.csproj" />
    </ItemGroup>

</Project>
