using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Edict.Generators;

/// <summary>
/// Emits a stable <c>[Alias]</c> partial for every concrete <c>partial record</c>
/// that derives from <c>Edict.Contracts.Events.EdictEvent</c>.
/// <para>
/// Discovery is semantic and by base type: the generator never
/// scans <c>Handle</c> bodies, so the publisher's assembly gets an alias even
/// when nothing local handles the event. By-name matching is preserved —
/// the alias is the simple type name, stable across namespace renames.
/// </para>
/// </summary>
[Generator]
public sealed class EdictEventGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var events = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is RecordDeclarationSyntax { BaseList: not null } candidate
                    && candidate.Modifiers.Any(static m => m.ValueText == "partial")
                    && !candidate.Modifiers.Any(static m => m.ValueText == "abstract"),
                static (ctx, _) => Map((RecordDeclarationSyntax)ctx.Node, ctx.SemanticModel))
            .Where(static model => model is not null)
            .Select(static (model, _) => model!);

        context.RegisterSourceOutput(events, static (spc, evt) =>
            spc.AddSource($"{evt.Namespace}.{evt.SimpleName}.Alias.g.cs",
                SourceText.From(EmitAlias(evt), Encoding.UTF8)));
    }

    private static EventModel? Map(RecordDeclarationSyntax syntax, SemanticModel model)
    {
        if (model.GetDeclaredSymbol(syntax) is not INamedTypeSymbol eventType)
        {
            return null;
        }

        if (!DerivesFromEvent(eventType))
        {
            return null;
        }

        var ns = eventType.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : eventType.ContainingNamespace.ToDisplayString();

        return new EventModel(eventType.Name, ns);
    }

    private static bool DerivesFromEvent(INamedTypeSymbol type)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == EdictWellKnownNames.EdictEventFqn)
            {
                return true;
            }
        }

        return false;
    }

    private static string EmitAlias(EventModel evt) =>
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace {{evt.Namespace}}
        {
            [global::Orleans.AliasAttribute("{{evt.SimpleName}}")]
            [global::MessagePack.MessagePackObjectAttribute(true)]
            public partial record {{evt.SimpleName}};
        }

        """;

    private sealed record EventModel(string SimpleName, string Namespace);
}
