using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Edict.Generators.Commands;

namespace Edict.Generators.Sagas;

/// <summary>
/// Per-command-type Saga Dispatch interceptor emitter (ADR-0034). One typed
/// specialisation method per discovered saga target Command, with N
/// <c>[InterceptsLocation]</c> attribute lines for every concrete-typed
/// <c>Dispatch(...)</c> call site inside a saga. The body forwards to
/// <c>EdictSaga&lt;TProgress&gt;.DispatchFast&lt;TCommand&gt;</c> so the typed
/// call site stays monomorphic; the buffer set is identical to the base
/// method (including the single-command-per-event throw).
/// </summary>
internal static class DispatchInterceptorEmitter
{
    public sealed record TypeBundle(
        string CommandFqn,
        string CommandSimpleName,
        EquatableArray<DispatchInvocationModel> Invocations);

    public static ImmutableArray<TypeBundle> Group(ImmutableArray<DispatchInvocationModel> invocations)
    {
        if (invocations.IsDefaultOrEmpty)
        {
            return ImmutableArray<TypeBundle>.Empty;
        }

        var byCommand = new Dictionary<string, List<DispatchInvocationModel>>(System.StringComparer.Ordinal);
        foreach (var invocation in invocations)
        {
            if (!byCommand.TryGetValue(invocation.CommandFqn, out var list))
            {
                list = new List<DispatchInvocationModel>();
                byCommand[invocation.CommandFqn] = list;
            }
            list.Add(invocation);
        }

        var builder = ImmutableArray.CreateBuilder<TypeBundle>(byCommand.Count);
        foreach (var commandFqn in byCommand.Keys.OrderBy(k => k, System.StringComparer.Ordinal))
        {
            var ordered = byCommand[commandFqn]
                .OrderBy(i => i.DisplayLocation, System.StringComparer.Ordinal)
                .ThenBy(i => i.LocationData, System.StringComparer.Ordinal)
                .ToArray();
            builder.Add(new TypeBundle(
                commandFqn,
                StripToSimpleName(commandFqn),
                new EquatableArray<DispatchInvocationModel>(ordered)));
        }

        return builder.ToImmutable();
    }

    public static string Emit(TypeBundle bundle)
    {
        var sanitised = SanitiseForIdentifier(bundle.CommandFqn);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("#nullable enable\n");
        sb.Append("\n");
        sb.Append("namespace Edict.Generated\n");
        sb.Append("{\n");
        sb.Append("    file static class DispatchInterceptor_").Append(sanitised).Append("\n");
        sb.Append("    {\n");

        foreach (var invocation in bundle.Invocations)
        {
            sb.Append("        // ").Append(invocation.DisplayLocation).Append('\n');
            sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(")
                .Append(invocation.LocationVersion)
                .Append(", \"")
                .Append(invocation.LocationData)
                .Append("\")]\n");
        }

        // Interceptor signatures must mirror the intercepted method exactly
        // (Roslyn 5.0). Dispatch lives on EdictSaga<TProgress>, so the
        // receiver is generic and TProgress gets inferred from the call-site
        // type. The per-command-type knowledge is preserved by a direct cast.
        sb.Append("        public static void InterceptDispatch<TProgress>(\n");
        sb.Append("            this global::Edict.Core.Sagas.EdictSaga<TProgress> self,\n");
        sb.Append("            global::Edict.Contracts.Commands.EdictCommand command)\n");
        sb.Append("            where TProgress : global::Edict.Contracts.Persistence.IEdictPersistedState, new()\n");
        sb.Append("            => self.DispatchFast<").Append(bundle.CommandFqn).Append(">((").Append(bundle.CommandFqn).Append(")command);\n");
        sb.Append("    }\n");
        sb.Append("}\n");
        sb.Append("\n");
        sb.Append("namespace System.Runtime.CompilerServices\n");
        sb.Append("{\n");
        sb.Append("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]\n");
        sb.Append("    file sealed class InterceptsLocationAttribute : global::System.Attribute\n");
        sb.Append("    {\n");
        sb.Append("        public InterceptsLocationAttribute(int version, string data) { }\n");
        sb.Append("    }\n");
        sb.Append("}\n");

        return sb.ToString();
    }

    static string StripToSimpleName(string fqn)
    {
        var trimmed = fqn.StartsWith("global::", System.StringComparison.Ordinal)
            ? fqn.Substring("global::".Length)
            : fqn;
        var lastDot = trimmed.LastIndexOf('.');
        return lastDot >= 0 ? trimmed.Substring(lastDot + 1) : trimmed;
    }

    static string SanitiseForIdentifier(string fqn)
    {
        var trimmed = fqn.StartsWith("global::", System.StringComparison.Ordinal)
            ? fqn.Substring("global::".Length)
            : fqn;
        var sb = new StringBuilder(trimmed.Length);
        foreach (var ch in trimmed)
        {
            sb.Append(ch is '.' or '<' or '>' or ',' or ' ' or '+' ? '_' : ch);
        }
        return sb.ToString();
    }
}
