using System.Linq;
using System.Text;

namespace Edict.Generators.Sagas;

internal static class SagaGrainSpineEmitter
{
    public static string Emit(SagaGrainModel grain)
    {
        var interfaceName = "I" + grain.GrainName;

        var streamNames = grain.Handlers
            .Select(h => h.StreamName)
            .Distinct(System.StringComparer.Ordinal)
            .OrderBy(n => n, System.StringComparer.Ordinal)
            .ToArray();

        var subscriptionAttrs = new StringBuilder();
        foreach (var name in streamNames)
        {
            subscriptionAttrs
                .Append("    [global::Orleans.ImplicitStreamSubscriptionAttribute(\"")
                .Append(name)
                .Append("\")]\n");
        }

        var handledTypeArms = new StringBuilder();
        foreach (var eventFqn in grain.Handlers.Select(h => h.EventFqn).Distinct(System.StringComparer.Ordinal))
        {
            handledTypeArms.Append("                    case ").Append(eventFqn).Append(":\n");
        }

        var dispatchArms = new StringBuilder();
        foreach (var handler in grain.Handlers)
        {
            dispatchArms
                .Append("                case ").Append(handler.EventFqn).Append(" typed:\n")
                .Append("                {\n")
                .Append("                    var link = ")
                .Append(EdictWellKnownNames.ActivityExtensionsFqn)
                .Append(".BuildLink(edictEvent.TraceId, edictEvent.SpanId, edictEvent.TraceState);\n")
                .Append("                    using var span = ")
                .Append(EdictWellKnownNames.ActivitySourceExtensionsFqn)
                .Append(".StartEdictEventHandle(")
                .Append(EdictWellKnownNames.EdictDiagnosticsActivitySourceFqn)
                .Append(", \"").Append(handler.EventSimpleName).Append("\", link);\n")
                .Append("                    if (span is not null)\n")
                .Append("                    {\n")
                .Append("                        ")
                .Append(EdictWellKnownNames.ActivityExtensionsFqn)
                .Append(".SetEdictConversationId(span, typed.ConversationId);\n")
                .Append("                        if (this.ServiceProvider.GetService(typeof(")
                .Append(EdictWellKnownNames.IEventTagWritersFqn)
                .Append(")) is ")
                .Append(EdictWellKnownNames.IEventTagWritersFqn)
                .Append(" __writers && __writers.TryGet(typeof(")
                .Append(handler.EventFqn)
                .Append("), out var __write)) { __write(typed, span); }\n")
                .Append("                    }\n")
                .Append("                    return await DispatchEventAsync(typed, ")
                .Append(EdictWellKnownNames.HandleMethodName)
                .Append(");\n")
                .Append("                }\n");
        }

        return $$"""
            // <auto-generated/>
            #nullable enable

            namespace {{grain.Namespace}}
            {
                /// <summary>Generated Orleans grain interface for {{grain.GrainName}}.</summary>
                public partial interface {{interfaceName}} : {{EdictWellKnownNames.IEdictSagaFqn}}
                {
                }

            {{subscriptionAttrs.ToString().TrimEnd('\n')}}
                public partial class {{grain.GrainName}} : {{interfaceName}}
                {
                    protected override async {{EdictWellKnownNames.TaskOfEdictDispatchOutcomeFqn}} DispatchAsync(
                        global::Edict.Contracts.Events.EdictEvent edictEvent)
                    {
                        switch (edictEvent)
                        {
            {{dispatchArms.ToString().TrimEnd('\n')}}
                            default:
                                return {{EdictWellKnownNames.EdictDispatchOutcomeNotHandledFqn}};
                        }
                    }

                    protected override bool HandlesEventType(
                        global::Edict.Contracts.Events.EdictEvent edictEvent)
                    {
                        switch (edictEvent)
                        {
            {{handledTypeArms.ToString().TrimEnd('\n')}}
                                return true;
                            default:
                                return false;
                        }
                    }
            {{EmitScheduleDispatch(grain)}}{{EmitScheduleTimeoutDispatch(grain)}}    }
            }

            """;
    }

    // Emits the schedule fire-dispatch type-switch — the parallel of the command
    // spine's DispatchScheduleFireAsync for the saga's
    // HandleAsync(TMessage) : Task<EdictScheduleResult> arms — only when the saga
    // registers at least one schedule. An un-annotated saga emits nothing here,
    // inheriting the throwing base default it can never reach.
    static string EmitScheduleDispatch(SagaGrainModel grain)
    {
        if (grain.ScheduleMessages.IsEmpty)
        {
            return string.Empty;
        }

        var arms = new StringBuilder();
        foreach (var message in grain.ScheduleMessages)
        {
            arms.Append("                ")
                .Append(message.Fqn)
                .Append(" m => this.")
                .Append(EdictWellKnownNames.HandleMethodName)
                .Append("(m),\n");
        }

        return $$"""

                    protected override {{EdictWellKnownNames.TaskOfEdictScheduleResultFqn}} DispatchScheduleFireAsync(
                        global::Edict.Contracts.Schedules.EdictScheduleMessage message) =>
                        message switch
                        {
            {{arms.ToString().TrimEnd('\n')}}
                            _ => throw new global::Edict.Core.Schedules.EdictUnroutableScheduleMessageException(
                                message.GetType()),
                        };

            """;
    }

    // Emits the schedule-timeout dispatch — the type-switch over the saga's
    // OnScheduleTimeoutAsync(TMessage) arms — only when the saga writes at least
    // one timeout hook. A fired cap whose message has no arm returns false so the
    // lifecycle dead-letters it; a saga with no timeout hook at all inherits the
    // base default (false for every message) and emits nothing here.
    static string EmitScheduleTimeoutDispatch(SagaGrainModel grain)
    {
        if (grain.ScheduleTimeoutMessages.IsEmpty)
        {
            return string.Empty;
        }

        var arms = new StringBuilder();
        foreach (var message in grain.ScheduleTimeoutMessages)
        {
            arms
                .Append("                case ").Append(message.Fqn).Append(" m:\n")
                .Append("                    await this.")
                .Append(EdictWellKnownNames.OnScheduleTimeoutMethodName)
                .Append("(m);\n")
                .Append("                    return true;\n");
        }

        return $$"""

                    protected override async {{EdictWellKnownNames.TaskOfBoolFqn}} DispatchScheduleTimeoutAsync(
                        global::Edict.Contracts.Schedules.EdictScheduleMessage message)
                    {
                        switch (message)
                        {
            {{arms.ToString().TrimEnd('\n')}}
                            default:
                                return false;
                        }
                    }

            """;
    }
}
